=== Zaretto/ReleaseBuilder/ReleaseConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="ReleaseConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string" minOccurs="0" />
        <xs:element name="Folder" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" />
            <xs:attribute name="name-version" type="xs:string" />
            <xs:attribute name="path" type="xs:string" />
            <xs:attribute name="version" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="Target" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Set" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" />
                  <xs:attribute name="value" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" />
            <xs:attribute name="path" type="xs:string" />
            <xs:attribute name="archive-version" type="xs:string" />
            <xs:attribute name="type">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="zip"/>
                  <xs:enumeration value="folder"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="Artefacts" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:choice maxOccurs="unbounded">
                <xs:element minOccurs="0" name="folder">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute name="skip-directories-front" type="xs:int" use="optional" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
                </xs:element>
                <xs:element name="build" minOccurs="0" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:choice maxOccurs="unbounded">
                        <xs:element name="clean" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:attribute name="folder" type="xs:string" use="required" />
                            <xs:attribute name="include-folders" type="xs:boolean" use="optional" />
                            <xs:attribute name="match" type="xs:string" use="optional" />
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="copy" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="transform-content" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                  <xs:attribute name="transform" type="xs:string" use="required" />
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                            <xs:attribute name="from" type="xs:string" use="required" />
                            <xs:attribute name="to" type="xs:string" use="optional" />
                            <xs:attribute name="match" type="xs:string" use="optional" />
                            <xs:attribute name="name" type="xs:string" use="optional" />
                            <xs:attribute name="recursive" type="xs:boolean" use="optional" />
                            <xs:attribute name="transform" type="xs:string" use="optional" />
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="modify" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="transform-content" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                  <xs:attribute name="transform" type="xs:string" use="required" />
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                            <xs:attribute name="file" type="xs:string" use="required" />
                          </xs:complexType>
                        </xs:element>
                        <xs:element minOccurs="0" maxOccurs="unbounded" name="xml-edit">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element minOccurs="0" maxOccurs="unbounded" name="node">
                                <xs:complexType>
                                  <xs:attribute name="path" type="xs:string" use="optional" />
                                  <xs:attribute name="action" type="xs:string" use="optional" />
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                            <xs:attribute name="file" type="xs:string" use="optional" />
                            <xs:attribute name="omit-declaration" type="xs:boolean" use="optional" />
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="exec" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:attribute name="app" type="xs:string" use="required" />
                            <xs:attribute name="args" type="xs:string" use="optional" />
                            <xs:attribute name="folder" type="xs:string" use="optional" />
                            <xs:attribute name="required-exit-codes" type="xs:string" use="optional" />
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="create" nillable="true" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:string">
                                <xs:attribute name="file" type="xs:string" use="required" />
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="release-builder" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Set" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                  <xs:attribute name="name" type="xs:string" />
                                  <xs:attribute name="value" type="xs:string" />
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                            <xs:attribute name="name" type="xs:string" use="optional" />
                            <xs:attribute name="folder" type="xs:string" use="optional" />
                            <xs:attribute name="process" type="xs:boolean" use="optional" />
                            <xs:attribute name="file" type="xs:string" use="optional" />
                            <xs:attribute name="nobuild" type="xs:boolean" use="optional" />
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:sequence>
                    <xs:attribute name="folder" type="xs:string" use="optional" />
                  </xs:complexType>
                </xs:element>
                <xs:element name="file" nillable="true" minOccurs="0" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute name="folder" type="xs:string" use="optional" />
                        <xs:attribute name="newname" type="xs:string" use="optional" />
                        <xs:attribute name="skip-directories-front" type="xs:int" use="optional" />
                        <xs:attribute name="name" type="xs:string" use="optional" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="folder" type="xs:string" use="optional" />
            <xs:attribute name="active" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element name="Artefact" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="folder" type="xs:string" use="optional" />
            <xs:attribute name="directory" type="xs:string" use="optional" />
            <xs:attribute name="file" type="xs:string" use="optional" />
            <xs:attribute name="root" type="xs:string" use="optional" />
            <xs:attribute name="newname" type="xs:string" use="optional" />
            <xs:attribute name="skip-directories-front" type="xs:int" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="ReleaseBuilder">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Set" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" />
                  <xs:attribute name="value" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="optional" />
            <xs:attribute name="folder" type="xs:string" use="optional" />
            <xs:attribute name="process" type="xs:boolean" use="optional" />
            <xs:attribute name="file" type="xs:string" use="optional" />
            <xs:attribute name="nobuild" type="xs:boolean" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Zaretto/ReleaseBuilder/ReleaseConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<ReleaseConfig xmlns:p1="http://www.w3.org/2001/XMLSchema-instance"
               p1:noNamespaceSchemaLocation="ReleaseConfig.xsd">

  <Name>ReleaseBuilder</Name>

  <!-- Windows x64 Target -->
  <Target name="win-x64" path="releases" type="zip" archive-version="~SemVer~">
    <Set name="RUNTIME" value="win-x64" />
    <Set name="PUBLISH_PROFILE" value="WindowsX64" />
    <Set name="OUTPUT_DIR" value="publish\release\win-x64" />
  </Target>

  <!-- macOS x64 Target -->
  <Target name="osx-x64" path="releases" type="zip" archive-version="~SemVer~">
    <Set name="RUNTIME" value="osx-x64" />
    <Set name="PUBLISH_PROFILE" value="OSX-x64" />
    <Set name="OUTPUT_DIR" value="publish\release\osx-x64" />
  </Target>

  <!-- macOS ARM64 Target -->
  <Target name="osx-arm64" path="releases" type="zip" archive-version="~SemVer~">
    <Set name="RUNTIME" value="osx-arm64" />
    <Set name="PUBLISH_PROFILE" value="OSX-arm64" />
    <Set name="OUTPUT_DIR" value="publish\release\osx-arm64" />
  </Target>

  <!-- Linux x64 Target -->
  <Target name="linux-x64" path="releases" type="zip" archive-version="~SemVer~">
    <Set name="RUNTIME" value="linux-x64" />
    <Set name="PUBLISH_PROFILE" value="Linux-x64" />
    <Set name="OUTPUT_DIR" value="publish/release/linux-x64" />
  </Target>

  <!-- Build Artefacts -->
  <Artefacts>
    <build>
      <clean folder="~OUTPUT_DIR~" include-folders="true" />
      <exec app="dotnet"
            args="restore"
            folder="~PUBLISHROOT~" />
      <exec app="dotnet"
            args="publish -p:PublishProfile=~PUBLISH_PROFILE~"
            folder="~PUBLISHROOT~" />
    </build>
    <folder>~OUTPUT_DIR~</folder>
  </Artefacts>

</ReleaseConfig>
